theme: jekyll-theme-minimal
remote_theme: pages-themes/modernist@v0.2.0
title: Fantasy Euroleague
description: Predict the winner and the difference on every euroleague match, and beat your friends 

# Layout
show_frame: true

# Menu
navigation:
- {title: "mac", file: "about.md"}
