theme: 
remote_theme: pages-themes/modernist@v0.2.0
title: Fantasy Euroleague
description: Predict the winner and the difference on every euroleague match, and beat your friends
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"


# Layout
show_frame: true
show_sidebar: true

# Menu
navigation:
- {file: "index.md", title: mac}
- {file: "README.md", icon: home}

external:
- {title: Mail, icon: envelope, url: "https://www.one.co.il/"}

plugins:
- jekyll-feed
